### ISSUE TITLE
.rubocop.yml for in-editor linting

### ISSUE THREAD

**Issue by lpil** [reevoo/reevoocop#2]
Hello

So I believe that most editor plugins look for a .rubycop.yml in the project dir for their rubocop conf, so the gem as it currently works wouldn't work for this.

Would anyone be against adding `.rubocop.yml` to app's gitignores, so we can symlink the config in without having to worry about accidentally committing it?

Cheers,
Louis

**Comment by jonnyarnold** [comment]
Sounds good to me.

**Comment by errm** [comment]
how do the plugins work . .  if they just shell out it should be good enough to alias reevoocop to rubocop in your `.profile`

**Comment by lpil** [comment]
This would mess with our ability to work on projects that don't follow our style guides.

[Here's how syntastic does it](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/ruby/rubocop.vim), does anyone speak vimL?

**Comment by jonnyarnold** [comment]
That would be a no then.
