### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/reevoocop#5]
We should come up with a way of ensuring our version number is updated whenever cop changes are made. This could be either:
1. Making sure we mandate it on Pull Requests to this repository.
2. Some clever githook for updating the version number when a Pull Request is merged into master.

Option 2 is obviously more work but more robust.

What do we feel?

**Comment by errm** [comment]
You have to bump the version before rubygems will accept another push.
I think there is a use case for wanting several pull requests in one version.

**Comment by jonnyarnold** [comment]
Fair enough!
