### ISSUE TITLE
`fail` and/or `raise`?

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/reevoocop#8]
Continued from https://github.com/reevoo/client_portal-admin/issues/22

Reasons for using `fail` and `raise`:
- Shows intent

Reasons for using `raise` only:
- Only one way of throwing errors
- Often practiced

**Comment by mikekr1** [comment]
Semantically it makes more sense to be able to differentiate what is happening by the word used, rather than just raising everything just because it means there is only one way of doing it.

**Comment by lpil** [comment]
I'm with @shyvy88.

**Comment by Antti** [comment]
@shyvy88 the guy is dead, so it doesn't matter anymore :japanese_goblin:

**Comment by errm** [comment]
Ruby is rubish anyway . . . lets make a new guideline that using ruby in your code should fail the build

**Comment by errm** [comment]
Srlsly though `fail` and `raise` is better . . .

**Comment by mikekr1** [comment]
@Antti Einstein is dead too yet we seem to keep following in his teachings.

**Comment by Antti** [comment]
@shyvy88 true.
I was kidding actually, but my point was that it's just one guy who suggested that. I didn't see Matz mentioning fail anywhere.

**Comment by Antti** [comment]
@errm why it is better to have and use 2 keywords for the same thing?  fail doesn't even have a syntax highlight in the most editors. And I've seen couple of gems which have their own fail method, which has nothing to do with exceptions.

**Comment by jonnyarnold** [comment]
@Antti Because you are doing two different things - there is a difference between creating a new error and passing one up the call stack.

**Comment by jonnyarnold** [comment]
There is no benefit to being consistent here. Everyone knows that `fail` and `raise` are the same thing, so there's no harm in using either. It's semantics vs. simplicity.
